### ISSUE TITLE
cannot count yet, plan fails on "filled"

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/use_bluesky#22]
Something wrong with the setup still.  Perhaps with the metadatabroker?
```
In [3]: RE(bp.count([noisy]))
 ...
~/Apps/BlueSky/lib/python3.6/site-packages/metadatastore/mds.py in insert(self, name, doc)
    717     def insert(self, name, doc):
    718         if name != 'bulk_events':
--> 719             getattr(self, self._INS_METHODS[name])(**doc)
    720         else:
    721             for desc_uid, events in doc.items():

TypeError: insert_event() got an unexpected keyword argument 'filled'
```

**Comment by prjemian** [comment]
Turns out that metadatastore and filestore modules have been deprecated.
The database setup is relocated in `~/.config/databroker/*.yml` files.


Such as `~/.config/databroker/mongodb_config.yml`:
```
description: 'heavyweight shared database'
metadatastore:
    module: 'databroker.headersource.mongo'
    class: 'MDS'
    config:
        host: 'otz.aps.anl.gov'
        port: 27017
        database: 'metadatastore-production-v1'
        timezone: 'US/Central'
assets:
    module: 'databroker.assets.mongo'
    class: 'Registry'
    config:
        host: 'otz.aps.anl.gov'
        port: 27017
        database: 'filestore-production-v1'
```

This is then called from `01-databroker.py` like:
```
from databroker import Broker
db = Broker.named("mongodb_config")
RE = bluesky.RunEngine()
```
