### ISSUE TITLE
use intake-style catalog

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/use_bluesky#76]
Following [this advice](https://blueskyproject.io/databroker/v2/administrator/index.html#administrator-documentation), switch `use_bluesky/admin/make_catalog.py` to use *intake-style* catalogs and store them per [recommendations here](https://blueskyproject.io/databroker/v2/administrator/index.html#search-path).

@danielballan : Thanks for the tip!
> [Bluesky] made an intentional choice to adopt intake-style configuration (both the format and the config directory location) and relegate databroker ones to backward-compatible legacy.

**Comment by prjemian** [comment]
Example [Broker-style](https://blueskyproject.io/databroker/v2/administrator/index.html#old-style-databroker-configuration-files) configuration file:

```
assets:
  class: Registry
  config:
    database: test1-file_refs
    host: poof
    port: 27017
  module: databroker.assets.mongo
description: heavyweight shared database
metadatastore:
  class: MDS
  config:
    database: test1-run_data
    host: poof
    port: 27017
    timezone: US/Central
  module: databroker.headersource.mongo
```

**Comment by prjemian** [comment]
Example [intake-style](https://blueskyproject.io/databroker/v2/administrator/index.html#intake-style-catalog-yaml-files) configuration file, using [mongodb](https://blueskyproject.io/databroker/v2/administrator/index.html#mongodb-example):

```yaml
sources:
  intake_test1:
    driver: bluesky-mongo-normalized-catalog
    args:
      metadatastore_db: mongodb://poof:27017/test1-run_data
      asset_registry_db: mongodb://poof:27017/test1-file_refs

```
