### ISSUE TITLE
registry of mongodb data repositories

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/use_bluesky#86]
As the number of Bluesky installations increases at APS, there is a distinct need to maintain a common registry of databases to enable *easily discoverable data repositories*.

Need tools to administer registry entries (add, update, freeze, archive).

Also, backups.

**Comment by prjemian** [comment]
Another motivation for this is to inform whether a proposed database repository is already in use.

**Comment by prjemian** [comment]
A web interface would be useful.

**Comment by prjemian** [comment]
Initially, using intake-style catalogs defined by YAML files, one single file could suffice.  YAML supports single-line comments so annotations are possible.

**Comment by prjemian** [comment]
Such as this catalog for 16-ID laboratory development:

```yml
sources:
    testlaue:
        args:
            asset_registry_db: mongodb://s100apps.xray.aps.anl.gov:27017/testlaue-file_refs
            metadatastore_db: mongodb://s100apps.xray.aps.anl.gov:27017/testlaue-run_data
        driver: bluesky-mongo-normalized-catalog
```
